### ISSUE TITLE
Docs for encoding seem out of date?

### ISSUE THREAD

**Issue by gkjohnson** [MONOGRID/gainmap-js#37]
Hello! I'm trying to encode a three.js RGBA float texture to a gain map and using the suggested snippet from the [Encoding](https://github.com/MONOGRID/gainmap-js?tab=readme-ov-file#encoding) section to try it. However I'm getting the following errors from parcel when building:

```
@parcel/core: node_modules/@monogrid/gainmap-js/dist/decode.js does not export 'compress'

  /Users/garrett/Desktop/git/three-gpu-pathtracer/example/hdr.js:17:10
    16 | import { LoaderElement } from './utils/LoaderElement.js';
  > 17 | import { compress, encode, findTextureMinMax } from '@monogrid/gainmap-js';
  >    |          ^^^^^^^^
    18 | import { encodeJPEGMetadata } from '@monogrid/gainmap-js/dist/libultrahdr.js';
    19 | import { WebGLPathTracer } from '..';

@parcel/core: node_modules/@monogrid/gainmap-js/dist/decode.js does not export 'encode'

  /Users/garrett/Desktop/git/three-gpu-pathtracer/example/hdr.js:17:20
    16 | import { LoaderElement } from './utils/LoaderElement.js';
  > 17 | import { compress, encode, findTextureMinMax } from '@monogrid/gainmap-js';
  >    |                    ^^^^^^
    18 | import { encodeJPEGMetadata } from '@monogrid/gainmap-js/dist/libultrahdr.js';
    19 | import { WebGLPathTracer } from '..';

@parcel/core: node_modules/@monogrid/gainmap-js/dist/decode.js does not export 'findTextureMinMax'

  /Users/garrett/Desktop/git/three-gpu-pathtracer/example/hdr.js:17:28
    16 | import { LoaderElement } from './utils/LoaderElement.js';
  > 17 | import { compress, encode, findTextureMinMax } from '@monogrid/gainmap-js';
  >    |                            ^^^^^^^^^^^^^^^^^
    18 | import { encodeJPEGMetadata } from '@monogrid/gainmap-js/dist/libultrahdr.js';
    19 | import { WebGLPathTracer } from '..';
```

Specifically the `compress`, `encode`, and `findTextureMinMax` functions to not seem to be exported from thethe main "gainmap-js" export (which maps to the dist/decode.js file). In fact I don't see any of those exports anywhere in the node modules distribution outside of comments. Is there a new recommended way to encode a FloatType RGBAFormat render target to a gain map?

Thanks!

**Comment by daniele-pelagatti** [comment]
Thanks for your contribution, I updated the README with up-to-date examples.

I need to find a way to automatically copy the code from `examples/` (which is always up to date) into the various readme, jsdoc comments, etc :smile:
