### ISSUE TITLE
Uploading file with .hdr.jpg extension online encoder fails

### ISSUE THREAD

**Issue by dmnsgn** [MONOGRID/gainmap-js#44]
Prompt with `Upload an HDR image please` when uploading a file renamed to `filename.hdr.jpg`.

You might be checking `.includes(".hdr")` instead of `.endsWith(".hdr")` when reading the file?

**Comment by daniele-pelagatti** [comment]
I was able to reproduce the problem, I'll have a look ASAP

**Comment by daniele-pelagatti** [comment]
This has now been solved, thanks for your feedback
